### ISSUE TITLE
label_cipcode.csv: better description, clarification on aggregation

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#122]
- needs better explanation of various levels (00 vs. 00.XX)
- display `CIPFamily` and explain
- needs better label definitions.

**Comment by srt1** [comment]
We will drop the 00.XX, 00.XXXX records. 

00 means "All instructional programs", end of story.

**Comment by srt1** [comment]
Please modify description in 6.15.2 (modification in bold):

CIP codes are sourced from the National Center for Education Statistics (NCES), Integrated Postsecondary Education Data System (IPEDS). Data are reported using 2010 CIP codes, for all years. In 4-digit CIP tabulations, **select** degree levels are collapsed to the 2-Digit CIP family, using custom codes (e.g., 01.XX, 02.XX, etc.).
