### ISSUE TITLE
Add IPEDS fields to earnings data

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#129]
We have added several variables sourced from IPEDS to the earnings file. We should also add some verbiage describing the source to the schema.

**Comment by jodyhoonstarr** [comment]
Do we want to add some text to go with this?

**Comment by srt1** [comment]
We could possibly add an note that "IPEDS counts sourced from [URL]." The documentation should have more info. We will also put together a more detailed explanation about the IPEDS status flags.

**Comment by andrewfoote** [comment]
Do we want a more detailed explanation for the schema, or should it just go into the documentation?

**Comment by srt1** [comment]
Sorry, I see I already wrote something up, and Jody has incorporated it. We can review it when it is all together, to see if it does the job.
