### ISSUE TITLE
status flags - ipeds

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#131]
We are adding an IPEDS count, which will have a special status flag. Thus I would like to add some subsections to section 7 in the schema.

https://lehd.ces.census.gov/data/schema/V4.4.0/lehd_public_use_schema.html#_status_flags

7. Status Flags

( label_flags.csv )

Most indicators in the LEHD data products have associated status flags. Each status flag in the tables above contains one of the following valid values. The values and their interpretation are listed in the tables below. Unless otherwise specified in this section, a status flag will take the values described in 7.1 Standard Status Flags.

7.1 Standard Status Flags

_[move the "Important Note" and graphic ! below 7.1]_

  | Important  Note: Currently, the J2J and PSEO tables only contain status flags '-1', '1',  '5'. Status flags with values 10 or above only appear in online  applications, not in CSV files.
-- | --

7.2 IPEDS Count Status Flag
(label_flags_ipeds_count.csv)

Graduate counts are provided from public use data from the Integrated Postsecondary Education Data System (IPEDS). Counts are linked to graduation cohorts in the PSEO data and included in the PSEOE tables. In a small number of cases, misalignment in programs (CIPCODE) is observed between the IPEDS and PSEO counts. In these cases, the IPEDS counts adjusted to be consistent with those on PSEO, and the count is flagged accordingly.

https://nces.ed.gov/ipeds/use-the-data

**Comment by jodyhoonstarr** [comment]
The text change was added but no label_flags_ipeds_count.csv seems to exist. @srt1 Drop it in the repo and we can link it.

**Comment by srt1** [comment]
Please add table display of IPEDS flags to section 7.2
