### ISSUE TITLE
ciplabel consistency issues

### ISSUE THREAD

**Issue by jodyhoonstarr** [labordynamicsinstitute/qwi_schemas#133]
There's some inconsistency in the labeling of cipcodes. 

1) The all label doesn't end in a period while others do. Can we just remove this in all cases? In userland I have to strip this out because periods have to be escaped in some use cases.

2) Looks like the value only gets quoted if there are commas in the string. Can we always quote string columns?

Trimmed down example:
> cipcode,label 
> 00,All instructional programs 
> 01,"Agriculture, Agriculture Operations, and Related Sciences."
> 03,Natural Resources and Conservation.

**Comment by jodyhoonstarr** [comment]
3) And can we get consistent cases on the labels.

e.g. 
All instructional programs -> All Instructional Programs

**Comment by srt1** [comment]
I will fix the capitalization, and strip the period on the label, which I agree is silly (not mine, was there on the source, of course).

I'd prefer not to futz with the quoting. The default for how the mechanism that creates them is to quote only if a comma is present. This is sensible, to the extent we don't want to to put quotes around other character fields, such as codes. It doesn't make the decision on a variable-by-variable basis, and you don't have the ability to change the rules, as far as I know. I'd rather not incorporate a custom CSV export macro at this time.

**Comment by jodyhoonstarr** [comment]
I'm fine with all of that
