### ISSUE TITLE
Modify XLS description in Section 5 

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#136]
**Section 5 - Basic Schema**

_Modify description as follows_

Each data file is structured as a CSV (comma separated values) file. The first columns contain [identifiers], subsequent columns contain [indicators], followed by status flags. In some cases, visually formatted Excel (XLSX) files are also available, containing the same information together with header lines on each sheet. Excel versions may contain labels following each identifier variable, and data may be abridged from the CSV due to size limitations.

**Comment by heathhayward** [comment]
works for me.

**Comment by srt1** [comment]
Possible addition - We could also modify the table in 5.1 as follows:


[ Identifier1 ]
[ label_Identifier1  (optional)]
[ Identifier2 ]
[ label_Identifier2 (optional)]
[ Identifier3 ]
[ label_Identifier3 (optional)]

Not sure how Lars would feel about this...

**Comment by larsvilhuber** [comment]
Hard to say from a cellphone on a French train...

--
Lars Vilhuber
on mobile device

________________________________

**Comment by srt1** [comment]
Mais oui.


(which is pretty much all of the non-cycling related French I know)

________________________________
