### ISSUE TITLE
mapping for identifiers - add PSEO

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#137]
PSEO was added to the identifier mapping, but the columns wrap improperly.

**Comment by jodyhoonstarr** [comment]
Huh? Where?
https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.5.0-draft/lehd_public_use_schema.html#_identifiers_for_pseo

**Comment by srt1** [comment]
Table in Section 5.2.1

**Comment by srt1** [comment]
https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.5.0-draft/lehd_public_use_schema.html#_mapping_for_identifiers
