### ISSUE TITLE
Describe version_pseo.txt

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#142]
**Section 8.1**

The PSEO will also include a version_pseo.txt file. Similar to QWI, there will be one per state, with several records describing the different tables (PSEOE, PSEOF). The most significant difference from the QWI/J2J specification is that the **start/end** values will not have quarters. They will be the first and last cohort_year (start of the cohort).  My suggestions:

* In _Source_ column, for **Start** and **End**
  * YYYY:Q (QWI, J2J)
  * YYYY (PSEO)

* At bottom of section, after comments about J2J version, add:

The PSEO metadata will contain separate lines for the PSEOE and PSEOF tables. The year range for PSEO tables is based on the **grad_cohort** _[ @jodyhoonstarr  - please link to grad_cohort in 6.16]_, the start year of the graduation cohort. An example for Colorado institutions has the following content:

_[link to version_pseo.txt for CO]_

**Comment by andrewfoote** [comment]
Example for Colorado:
PSEOE CO 08 2001-2015 V4.5.0 2019Q1 pseopu_co_20190617_0839
PSEOF CO 08 2001-2015 V4.5.0 2019Q1 pseopu_co_20190617_0839

**Comment by jodyhoonstarr** [comment]
Please review and close issue if fixed.

**Comment by srt1** [comment]
Just for readability, please stick a space or two between yyyy:q or yyyy and the parenthesis, please.
