### ISSUE TITLE
Plain language names for the QWI

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#17]
See email thread.

**Comment by larsvilhuber** [comment]
[variables_qwipu2.xlsx](https://github.com/labordynamicsinstitute/qwi_schemas/files/199739/variables_qwipu2.xlsx)

**Comment by heathhayward** [comment]
[variables_qwi2.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/204966/variables_qwi2.zip)

**Comment by heathhayward** [comment]
[variables_qwi2.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/206940/variables_qwi2.zip)
Here is the most current file.

**Comment by larsvilhuber** [comment]
Verify, and potentially close.

**Comment by larsvilhuber** [comment]
Looks to be in v4.1d-draft.
