### ISSUE TITLE
fix misspelled indicator and status flag names in the variables_qwipu, variables_qwi, variables_qwir, variables_qwiv, and variables_qwirv csv files 

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#18]
in the V4.0 and V4.1 draft schemas.

**Comment by larsvilhuber** [comment]
Just noticed today that the "variables_qwipu.csv" file in the V4.0 schema versions incorrectly spells the FrmJbLs and EarnHirNS indicators (and their Status Flags), they say FrmJobLs and EarnHireNS (notice the "o" and "e"):

http://lehd.ces.census.gov/data/schema/V4.0.4/variables_qwipu.csv

The V4.1 draft schemas have the indicator spelled correctly but their status flags are incorrectly spelled:

http://lehd.ces.census.gov/data/schema/V4.1c-draft/variables_qwi.csv

The qwir, qwiv, and qwirv csvs in the V4.1 draft schema also have these misspellings.

**Comment by heathhayward** [comment]
Where can I review the updated csvs?  Just want to make sure you updated the capitalization of HirAS and HirNS (and their status flags) in these files as well.

**Comment by larsvilhuber** [comment]
should be updated in all of these files. You can navigate through the file structure, and through the associated commits.


https://github.com/labordynamicsinstitute/qwi_schemas/blob/master/formats/V4.0.5/variables_qwipu.csv

labordynamicsinstitute/qwi_schemas<https://github.com/labordynamicsinstitute/qwi_schemas/blob/master/formats/V4.0.5/variables_qwipu.csv>
github.com
qwi_schemas - Experimenal QWIPU Schema files





--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD
lars.vilhuber@cornell.edu |  +1.607-330-5743
Assistant: ldi@cornell.edu | +1.607-255-2744

http://www.vilhuber.com/lars/
GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346



________________________________
