### ISSUE TITLE
Add variable DESCRIPTION field to QWI variable metadata

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#30]
We need a description field in the QWI metadata.

**Comment by larsvilhuber** [comment]
@heathhayward : bump on this

**Comment by heathhayward** [comment]
A Description field exists in https://lehd.ces.census.gov/data/schema/V4.2a-draft/variables_qwi.csv.  The qwir, qwirv, and qwiv csv files are missing a Description and Concept field though. Although I'm not super familiar with these files, I can take a crack at adding these fields if you like.

**Comment by larsvilhuber** [comment]
Moving this to V4.2.0 (final) pending resolution.

**Comment by larsvilhuber** [comment]
Reminder that we need to finalize this for 4.2.0

**Comment by srt1** [comment]
Please provide full specs for any added fields so that they can be incorporated into the production QWI metadata table. All schema files should be produced directly from that table (see #71).

**Comment by srt1** [comment]
See also [Redmine 1699](http://otm-vc2trac.dev.ces.census.gov/issues/1699)

**Comment by larsvilhuber** [comment]
@srt1 : can you attach the files you've generated from the internal ones?

**Comment by srt1** [comment]
Trying to keep these straight; I'm trying to accomplish several tasks with the updated *_measures.csv tables, and they don't line up with the tickets, unfortunately.

I have prepared updated qwi_measures.csv and qwir_measures.csv driven off the metadata, with additional features and the same layout as the J2J ones. I think the main outstanding question is what we call the concept for the JF family of measures. Is "Job Change" OK? "Firm Job Change"? I think we had some resolution to the other questions, noted in #71.

**Comment by larsvilhuber** [comment]
Waiting for feedback from Erika @srt1 handling.

**Comment by larsvilhuber** [comment]
Wrong ticket. This one is closed.
