### ISSUE TITLE
Geovintage 2016 changes to label files

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#34]
Camille reports changes to 2016 Counties

**Comment by larsvilhuber** [comment]
[2016_GeoVintage_Upgrade_(Updated_Label_Geography_Files).zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/437436/2016_GeoVintage_Upgrade_.Updated_Label_Geography_Files.zip)

**Comment by larsvilhuber** [comment]
@heathhayward : all the changes in these files are for Metropolitan areas. This suggests that the LEHD Shapefiles also need to be updated, to be in sync. Could you provide them?

**Comment by heathhayward** [comment]
2016 geovintage LEHD Shapefiles will be added to the schema when they are ready (Nov 2016).   To notify users of this timing, how about adding the following lines to the end of the "Scope" section of the "lehd_shapefiles.pdf/html":

"New TIGER/Line shapefiles are typically released by the Census Bureau's Geography Division in August of each year, which are then processed by the LEHD program as new tabulation areas for the QWI and J2J data products.  The LEHD shapefiles will be made available in the data schema in coordination with the public release of QWI and J2J data products, usually in November or December of each year.
