### ISSUE TITLE
label_geography_cbsa contains micro areas, does not include residual regions. It may also be misnamed.

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#39]
The label_geography_cbsa includes micropolitan areas, though we are not planning to tabulate on them. 
It also does not include the statewide residual regions, which are the non-metro areas within a state, including the micropolitan area. This later should probably not define effectively overlapping regions, where the residual and micro areas overlap.

We may also want to change the name from _cbsa to something else. (label_geography_msa?)

**Comment by larsvilhuber** [comment]
Requesting clarification for V4.1.1 - there are three issues here: 
- micropolitan areas not (currently?) used for tabulation
- rename to MSA if removing micropolitan areas from the file
- Are the "balance" areas the non-(metro+micro) areas, or the non-(metro only) areas? 

This suggests possibly creating a new file _msa with only reference to metro and their state balances. This also means switching what the "geo_level=b" files refer to (ironically, the "b" came from cBsa...") Coding for balance areas should be similar to but distinct from the geo_level=m balance areas.

Unless LEHD will NEVER tabulate to micro areas, I suggest keeping this file as is (i.e., all legal values, but not all actually-tabulated areas), but add an indicator for metro and micro (as in the source data), and adding the balance areas (both for non-(metro,micro) and non-metro)

**Comment by srt1** [comment]
Micropolitan areas are not tabulated in J2J. I believe we were going to rename the region MSA, which is the set of metropolitan regions, plus the state residual (non-metro in each state). Micropolitan areas are included in the state residuals. The residuals are different than the "M" residuals: those are SS99999, whereas the "B" ones are SS999. The state-part MSA codes  are prefixed with the state code, so they have 7 characters, the B ones are just the MSA code, so they have 5. We could propose SS998 as non-metro/non-micro, and SS999 as non-metro residual.

Heath might argue that he would want the definition to be mutually exclusive and complete, but my opinion on that is not strong. Obviously, you would never see SS999 in conjunction with SS998 or micro areas in any tabulation.

**Comment by larsvilhuber** [comment]
Quick resolution regarding the CBSA/MSA discussion:

* the tabulations currently only use MetroSA and (MetroSA-balance) areas
* Heath's shapefiles only define the same shapes
* the Schema describes the "b" geo_level as (potentially) all metro and micro areas, plus the balance of (non metro, non micro) (?)
* the app only shows what the shapefiles and the data allow it to do

I believe it is also correct to state that the "geo_level = b" is only used by J2J, and that no micro areas have been used so far.

If the above is correct, I am OK with re-purposing (redefining), in part RETRO-actively (as a correction) V4.1.x files to make the geo_level= b be clearly only METRO areas.

I need positive confirmation, and consent to this before proceeding.

This is holding up V4.1.1.

**Comment by larsvilhuber** [comment]
Changed to V4.1.1 because it intersects with the shapefiles #45

**Comment by larsvilhuber** [comment]
@srt1 @heathhayward : please create a label_geography_metro.csv that is used instead of label_geography_cbsa.csv by J2J. it should contain only Metro + remainder areas, as per the SHP files.

**Comment by heathhayward** [comment]
I'm ok with what you've proposed.  We could/should replace the label_geography_cbsa file with a label_geography_metro file.

**Comment by larsvilhuber** [comment]
@heathhayward : could you please create the _metro file as specified?

**Comment by heathhayward** [comment]
Does this work?
[label_geography_metro.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/822641/label_geography_metro.zip)

**Comment by heathhayward** [comment]
it's the same attribute table as in the "gb" shapefile, except with the geo_level column added.

**Comment by larsvilhuber** [comment]
OK, this looks good. 

Is an alternate description of the shapefile that "attributes are taken from (label_geography_something).csv, the geo_level column removed, and boundaries adjusted" (or some other way to establish link/coherence between the shape file( package)s and the CSV files?

**Comment by heathhayward** [comment]
Could we just say that the contents of the label geography files align with the lehd shapfiles?
