### ISSUE TITLE
Add earnings measures to J2J 

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#41]
The J2J and J2JOD products will have earnings measures added to the csv files

**Comment by larsvilhuber** [comment]
@srt1 : Is this in your V4.2a-draft or V4.2b-draft files? If in V4.2b-draft, please reclassify this issue to the right milestone.

**Comment by srt1** [comment]
[j2j_variables_v2.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1200934/j2j_variables_v2.zip)
Attached is the latest copy of the schema files for the J2J variables, intended for 2017Q2 production release (August 2017)

**Comment by heathhayward** [comment]
a couple comments:
- For the earnings measure names, the count measures have a capitalized "_Origin" and "_Dest" but the OD measures have lower case "_orig" and "_dest".
- should "NEHiresSEarn_Dest" come after "ENSepSEarn_Orig"?  All of the other earnings measures list the origin earnings first.
- In the Indicator Name field for "MainBS" and"MainES", I think parentheses should be used instead of brackets around "Beginning/End of Quarter" - at least that's the standard used elsewhere.
- Might be worth noting: for V4.1.2 (which I think is the most current published schema), only the variables_j2jr.csv file has a "Base" field.  That field is now in the j2j and j2jod variables file as well.

**Comment by heathhayward** [comment]
regarding my last comment above, if we are following the formats of previous "draft" schemas, these files should all include the "Description" and "Concept" fields (as shown here: https://lehd.ces.census.gov/data/schema/V4.2a-draft/variables_j2j.csv).

**Comment by srt1** [comment]
Thanks for the comments. Responses:

* Thanks for catching the capitalization, I should be able to fix that without impact
* That's a quirky one. These earnings are done in the order that the corresponding base variables are listed, which is the hire before the separation. It was an unfortunate choice, perhaps - in a job history, you think of the hire occurring before the separation, but in J2J in a quarter, the separation measures are chronologically before the hire. Hence, we've dug ourselves into a little inconsistency. My sense of the earnings measures is that they should follow the sequence in the base counts, as they have been presented. I could reverse them, but I would prefer not to reverse the base counts, which leads to significantly more complications.
* Will review parenthesis vs. brackets
* I was intending to build off the 4.2a-draft which does have the base for all products. I didn't realize (or had lost track) that it also had the description/concept fields. Those are not part of the program I used to generate the files last time, so you must have added them manually. If we are agreed to keep those variables on these files, I'll add them so you don't have to do the manual intervention. It's also possible you made some label edits that didn't find their way back to my metadata table.

**Comment by heathhayward** [comment]
Sounds good.  as you say, I may have manually added those fields.  I'm happy for you to be the official source of these files (with the exception of the j2japp file that I create manually).

**Comment by srt1** [comment]
Attached are csv files for the indicators (J2J/J2JR/J2JOD) including the description/concept fields.

[vars-schema-4.2b-draft.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1205522/vars-schema-4.2b-draft.gz)

**Comment by srt1** [comment]
Minor edits to labels

[vars-schema-4.2b-draft.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1205724/vars-schema-4.2b-draft.gz)

**Comment by heathhayward** [comment]
you've got two extra header rows in there.  rows 33 and 42.  And rate measures shouldn't be listed in variables_j2j.csv

**Comment by srt1** [comment]
More fixes. Labels now say "quarterly" earnings.

[vars-schema-4.2b-draft.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1205923/vars-schema-4.2b-draft.zip)

**Comment by heathhayward** [comment]
looks good to me

**Comment by srt1** [comment]
As per #60, modified "concept" fields for MJobStart/MJobEnd.
[vars-schema-4.2b-draft.tar.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1212946/vars-schema-4.2b-draft.tar.gz)

**Comment by larsvilhuber** [comment]
@srt1 @heathhayward : I'm assuming these files also address #54 . Checking now.

**Comment by srt1** [comment]
**Heath:**

Note, the J2JOD count measures are now labeled as _hire_ rather than _flow_. This is consistent with what they are as measures - there is no difference between a hire on the J2J file versus the J2JOD file. The J2JOD file simply tabulates that measure by both the origin and destination characteristics, rather than just one or the other. You may need to handle this somewhat differently in your APP control stuff.

**Comment by srt1** [comment]
Lars - Heath may have a question about my last comment, but is out this week. Do you have an opinion about how the J2JOD measures are characterized in the concept field?

**Comment by larsvilhuber** [comment]
Other than "consistently with J2J", no.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Well, the measures are named differently, but that was done for separate reasons - the EE measures have dropped the "Hire" word, though the AQ measures keep it (I would have preferred that we keep the measure names the same in J2J and J2JOD, frankly). The measures are referencing the flows by the quarter of hire, though they are referred to as "flows" in their descriptions. 

In my internal metadata table for the measures, the EEHire measure has an alternate name for the OD table - it is the same row. Hence, they are both getting the same concept. If we want to give them an alternate concept for J2JOD, I could create a secondary concept field, but my preference would be to leave them the same.

**Comment by larsvilhuber** [comment]
If they are the same "variable" (regardless of the name of the variable), then they should get the same concept. No secondary concepts, one has generated enough of a discussion...


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Well, they are the same variable, in most senses, though it did give us a notation headache in the long documentation. We resolved to give one version 3 subscripts (ee_doma2<sub>ikt</sub>), and the other 4 (ee<sub>ijkt</sub>). See https://lehd.ces.census.gov/doc/jobtojob_documentation_long.pdf, table 1 (Employer to Employer Transitions).  It is also explained in section 2.1.1, Eq 2.8 and 2.10. One is described as the "Transition" (2.8), which is broken into a Hire (2.10) and a Separation (2.9). 

We do indicate that the measures are the same in the "Variable Relatedness Diagram. "
https://lehd.ces.census.gov/doc/help/j2j_explorer/J2JVariableRelatedness.pdf

I really don't know what is best here for the concept field. It's a matter of interpretation and use - and I am not the one using it.

**Comment by larsvilhuber** [comment]
It's a matter of definition, and computation. If they are the same computation, then it's the same concept.

--
Sent from my mobile

________________________________

**Comment by srt1** [comment]
Well, at the micro level,  _ee_doma2<sub>ikt</sub>_ is 1 if there exists a _j_ such that  _ee<sub>ijkt</sub>_ is 1. So that's pretty much the same thing.

**Comment by larsvilhuber** [comment]
That last change should really have been attached to #60

**Comment by srt1** [comment]
These changes look correct, concepts may be reviewed again in a later iteration.
