### ISSUE TITLE
Create customized schema description files

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#42]
* create a "lehd_j2japp_schema.html" which is a focused subset of the overall schema, for the J2J app
* create a "lehd_j2j_schema.html", which is focused on the J2J CSV files ONLY.

**Comment by larsvilhuber** [comment]
@heathhayward : bump for this one. Check out the lehd_j2jexplorer_schema.html  (you'll need to download it, haven't pushed it to my web server yet)

**Comment by heathhayward** [comment]
I'm fine with what you've done with https://lehd.ces.census.gov/data/schema/V4.2a-draft/lehd_j2jexplorer_schema.html.  My only comments are: 
- Users may be confused to see QWI indicators mentioned in 5.2.1 and 5.2.4 (the "mapping indicators" and "qwi indicators").  Are those necessary to include in a page specific to J2J Explorer?
- There will be a few updates to this content when the 1.0 version of data is released. I will provide updates when I have more information.
- Don't really want to make more work for us, but should there be a QWI Explorer page in the schema?

**Comment by larsvilhuber** [comment]
@heathhayward 

- I have removed the QWI identifiers; oversight...
- These pages are NOT part of the schema, rather, they are meant to be views ONTO the schema. (but for ease of reference, they are within the schema directory). The key thing is: they are an example of how you can generate all of the details purely from the schema. Something like this could also be integrated into the app itself - as long as it references directly the schema files (the csv files).
- Apart from that minor point, yes, there could be a QWI Explorer page. Or rather: a QWI-only, a J2J-only page (I don't really care about the app itself - it just happens to make available only one portion of the data).

**Comment by srt1** [comment]
Is there anything I need to look at here? I'm not sure exactly I would need to review, if so.

**Comment by larsvilhuber** [comment]
Heath already did. It's the HTML versions wittled down to specific applications (the j2japp in his case). We could do this for QWI and LODES as well - it removes all parts of the schema from the human-readable HTML/PDF version that are not relevant to that data/application.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
looks good.
