### ISSUE TITLE
Correct variables_j2j* files

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#43]
The schema describes the SPECIFIC files that we describe. So if we create two very similar files, we should be creating TWO separate descriptions. And because they are formal descriptions, they WILL be repetitive if they are very similar.

So yes, if the APP outputs two additional vars, then there is going to be a SEPARATE variables_j2jod_app.csv, although I'm guessing that a "variables_j2japp.csv" that describes all potential variables output by the app is better.

That being said, what I meant by separate documentation is that the APP itself might have a separate human readable document, that lists only the relevant files, and the J2J CSV files has a separate human readable document, that does not list the APP schema. However, the directory would have ALL of these files.

We have not run into this issue before because (correct me AND the schema if this is wrong), the QWI-related apps output a SUBSET of the QWI CSV files, whereas here the app is doing a SUPERSET of the CSV file vars.

So my proposal is:

Heath/Stephen:
* correct variables_j2jod.csv (remove the vars that are not on there)
* create variables_j2japp.csv

**Comment by larsvilhuber** [comment]
See also #40

**Comment by heathhayward** [comment]
Corrected files in #40

**Comment by larsvilhuber** [comment]
The j2jod file was corrected in b076ed1 . the j2japp file will be implemented in V4.2a-draft.
