### ISSUE TITLE
Update "lehd_shapefile" pdf, html, md content to reflect 2016 geographies

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#45]
The geography information located in https://lehd.ces.census.gov/data/schema/V4.1.1/lehd_shapefiles.html (as well as the pdf and md versions) need some updates.  Here are my suggested edits:

- in the Scope section, change "Job-to-Job Explorer (coming soon)" text to "Job-to-Job Explorer".

- in the Sources section, change text and links to refer to 2016 TIGER/Line vintage.

- in the Basic Naming Schema, can we change the "gm" description to say "Metropolitan/Micropolitan (state parts)" and the "gb" desciption to "Metropolitan (complete)"?

- in the 5.5 Job-to-Job Flows Geographies section, the 5.5.1 title should say "Metropolitan Areas - National" instead of "CBSA - National". The text underneath should add a note about removing micropolitan areas, so could now read: "Micropolitan areas are removed and state remainder areas are added as new features. State remainders are assigned unique codes ([STUSPS]+999) and names (“Not in metropolitan area, [STUSPS]”).

**Comment by larsvilhuber** [comment]
The clarification of the GB to refer only to Metropolitan is not ready for implementation. See related discussion in #39 . I need clarity as to where the "gb" geographies are being used to assess whether this is a minor or a major change. Switching all discussions to #39.
