### ISSUE TITLE
Replace label_geography_cbsa with label_geography_metro?

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#50]
Or was this not a 4.1.1 change?

**Comment by larsvilhuber** [comment]
See #39 and cf4c9046c429d371be4d163b31161da504177001

**Comment by larsvilhuber** [comment]
I changed the REFERENCE to label_geography_metro.csv, but did not remove the CBSA file.

**Comment by heathhayward** [comment]
I see the metro file now.  Should we remove the cbsa file since they reference the same "B" geo_level?  Also noticed that the "B" geo_level geographies are not included in the label_geography.csv file.  This is not new, but I thought that csv contained all LEHD geographies.

**Comment by heathhayward** [comment]
ok

**Comment by larsvilhuber** [comment]
The label_geography.csv file has in the past only contained the state-level geo files. I didn't want to mess that up now by adding new things on the fly. We'll make that a 4.2 issue.
