### ISSUE TITLE
Extensions to csv file naming: sarhe

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#52]
All metro tabulations have been collected in a single file, tagged sarhe.  For example, j2jod_01999_sarhe_f_gb_ns_oslp_u.csv.gz. 

The sarhe needs to be added to:
https://lehd.ces.census.gov/data/schema/V4.1.0/lehd_csv_naming.html#_demo

**Comment by srt1** [comment]
The state naming also needs to be expanded to include the 5-digit CBSA codes (metro-only used for J2J)

https://lehd.ces.census.gov/data/schema/V4.1.0/lehd_csv_naming.html#_geohi

The comment at the top of this section also says "...alphabetic FIPS state code ..."; is the alphabetic code a FIPS code or just a postal code?

**Comment by larsvilhuber** [comment]
Alphabetic was, in fact, part of the FIPS code. The ANSI code as maintained at the Census Bureau refers to it as "US Postal Codes".

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by srt1** [comment]
The **version_j2j.txt** and **version_j2jod.txt** file for the metro regions will also use "METRO" as the second word in the line, where the state postal code or "US" would go. 

The version file for metro will also have one line for each metro region (may not require noting in the schema).

**Comment by larsvilhuber** [comment]
@srt1 : can you provide an example in this ticket for the proposed "geohi" naming schema addition? note that the text you refer to itself refers to "naming_geohi" which should contain all legal values for that part of the naming convention?
