### ISSUE TITLE
J2JOD - renaming stable count variables

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#53]
The following variables will be renamed on J2JOD:

EEFullQ -> EES
AQFullQHire -> AQHireS

There was significant confusion that "FullQ" was used to refer to both full quarter employment (3 consecutive quarters) and full quarter nonemployment (no earnings from any job in a quarter). We are changing the names of the employment measures to have a trailing S to indicate "Stable," which is the convention used in QWI.

**Comment by heathhayward** [comment]
What vintage of J2J will this first appear in?  2016Q4?  or 2017Q1?

**Comment by srt1** [comment]
My proposal was to change this in 2016Q4.

**Comment by larsvilhuber** [comment]
This was implemented in 20fccc89d2da01629adce4364793e5775a2ae0e7
