### ISSUE TITLE
errors in the existing variables_j2jr.csv : "Rate" instead of "R"

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#54]
errors in the existing variables_j2jr.csv file. For three of the variables, the status flag has a suffix of "Rate" instead of "R". I think that this file was meticulously crafted for purposes of the web app, rather than being created directly from the internal J2J metadata.

**Comment by larsvilhuber** [comment]
@heathhayward @srt1 : could you check this ambiguity here about the suffix of "Rate" vs "R"

**Comment by srt1** [comment]
I think this was an issue with 4.1.0. Three of the status flags have "Rate" at the end. That should be just "R". The convention on the "alternate name" is to use _rate (for whatever reason).

https://lehd.ces.census.gov/data/schema/V4.1.0/lehd_public_use_schema.html#_job_to_job_flow_rates_j2jr

I have provided updated variables csv files intended for  V4.2b-draft in another ticket.

**Comment by srt1** [comment]
The 4.2*-draft schema have not had this issue, it is a problem with the 4.1* schema. The 4.1.0 schema is the official one of record for the 2016Q3 release, but since then we moved J2J onto 4.2*. Do we want to retroactively correct the 4.1.* schema, or leave it as-is? QWI are still on 4.1.2, which has these misnamed J2J variables. It's a minor historic quirk, perhaps not worth the effort, but up to you.

**Comment by larsvilhuber** [comment]
For this purpose, there are two questions:


- are any J2J releases referencing the 4.1.x series?


If yes, then a correction is in order. If not, we can pull it into 4.1.3 and be done with (currently, the 4.1.3a-draft branch variables_j2jr.csv is unchanged from V4.1.2).

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
As noted, yes, the 2016Q3 release references 4.1.0. Later 4.1.x schema are not referenced. 

https://lehd.ces.census.gov/data/j2j/R2016Q3/j2j/ak/version_j2j.txt
`J2J  AK 02  2000:2-2015:3  V4.1.0 R2016Q3 j2jpu_ak_20161028_1522`

**Comment by larsvilhuber** [comment]
Then yes, we should edit the previous versions to be correct.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by larsvilhuber** [comment]
Need to fix in releases 4.1.0 - 4.1.3

**Comment by larsvilhuber** [comment]
All prior releases of V4.1.x fixed in the V4.1.3a-draft branch. Will be pulled forward once we sign off on that version.

**Comment by srt1** [comment]
Versions 4.1.0 to 4.1.3 look correct now.
