### ISSUE TITLE
WIB shapefile change for R2017Q4 QWI Vintage

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#61]
A WIB area in TX (Alamo WDA. 48000020) gained a county (McMullen, 48311) and an adjacent WIB area (Coastal Bend WDA, 48000022) lost a county.  No change to any of the label_geography files (no change in WIB names or codes), so the only item in the schema that will need to be updated is the attached WIB shapefile.  Let me know if you have any questions.

[lehd_shp_gw.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1216310/lehd_shp_gw.zip)

**Comment by srt1** [comment]
Closing as per Jody's review

```
From: Jody Alexander Hoon-Starr (CENSUS/CES FED)
Sent: Monday, August 21, 2017 3:17 PM
To: lars.vilhuber@cornell.edu; 
Subject: Re: Schema "git Milestone": V4.1.3 PLEASE REVIEW
 

Can confirm that the wib file in the V4.1.3a-draft branch contains the county change listed in issue #61. 


```
