### ISSUE TITLE
Broken link to metro page

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#62]
From Matt:

For the next version please update the metro links in section 6.14 from http://www.census.gov/population/metro/ (broken) to https://www.census.gov/programs-surveys/metro-micro.html

And anywhere else if relevant.

**Comment by heathhayward** [comment]
This is a simple edit to the label_geo_level.csv file.  The url in the "sourceurl" column for "geo_level" B and M should be changed to https://www.census.gov/programs-surveys/metro-micro.html.  Lars, let me know if you need me to attach an edited csv here.

**Comment by srt1** [comment]
This seems right; were we going to fix the earlier versions (4.1.0, 4.1.1, 4.1.2), or leave as-is?

**Comment by larsvilhuber** [comment]
We are not fixing earlier versions. in fact, at the time they were published, those links were working...


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
I was guessing that, just confirming.
