### ISSUE TITLE
section 8.1 - version.txt description "geo" component a little off

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#69]
The "geo" component is described as [stusps] or Metro. The description says "uppercase state postal code or the word MSA". It should say "... the word METRO".  There's also an extra space where it says [ stusps]

We also might want to clarify what we mean by Numeric (FIPS) geography code in the "fips" section - if metro cods are not FIPS codes, and our special "nonmetro" ones definitely are not.

```
J2JR METRO 01999 2001:2-2016:2 V4.2b-draft R2017Q2 j2jrpu_us_20170714_2008
J2JR METRO 02999 2000:4-2016:1 V4.2b-draft R2017Q2 j2jrpu_us_20170714_2008
J2JR METRO 04999 2004:2-2016:2 V4.2b-draft R2017Q2 j2jrpu_us_20170714_2008

```

**Comment by srt1** [comment]
You still have a phantom space before  [ stusps], possibly an underscore

`
[_stusps] or METRO

`

**Comment by srt1** [comment]
Should we explicitly add US, or are we rolling that into uppercase state postal codes?

**Comment by srt1** [comment]
Just paging over to try to understand the changes a little better. Yes, I'm pretty sure that we should change this to [stusps], US, or METRO

I see the STUSPS is there, and US is not a state.

**Comment by heathhayward** [comment]
I'm fine adding the following line to the top of the stusps file

"00","US","United States of America"

**Comment by heathhayward** [comment]
or the label could be left as it is "National (50 States + DC)".  Not sure which is better (or more accurate)
