### ISSUE TITLE
Add "File Structure" heading to highlight link to QWIPU naming conventions page

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#7]
At the top of the LEHD data schema page, please add a new section that will contain the existing sentence with the lehd_csv_naming.html link.  This should help users find this information about how to parse out the QWIPU naming conventions.  The lend_csv_naming.html file should probably reciprocate this format by bolding the links back to the data schema page. Thanks.

**Comment by larsvilhuber** [comment]
Implemented.
