### ISSUE TITLE
Add info on lags for J2J/QWI measures

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#71]
Measures have varying quarters of data required before or after the reference quarter to be released. This is part of both the J2J and QWI metadata, but is not provided to the public or the application. We can add columns to the variables_*csv files. Name suggestions:

quarters_required_prior
quarters_required_subsequent

More elegant names would be welcome.

**Comment by srt1** [comment]
[j2j_measures.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1344572/j2j_measures.zip)

Sample schema files with added info (draft)

**Comment by heathhayward** [comment]
Excensus approves of this addition.  It will help the application provide users with the exact cause of a "No Data" error. Let's make this a part of the next schema version.  I'm ok with the column names - not the most elegant but they are appropriately descriptive!

**Comment by heathhayward** [comment]
I'll make a "variables_j2japp.csv" file and add it to this ticket.

**Comment by srt1** [comment]
The J2JOD measures table will also have to be corrected because of the description issue in #72. I'll post an update.

**Comment by srt1** [comment]
I seem to have tagged adding the quarters before/after to the 4.3 schema; is there any reason we can't add this to 4.2, both for J2J and QWI? Just wondering. I'm losing track of the overall gameplan for the schema evolution again.

**Comment by larsvilhuber** [comment]
This is up to you. I'm happy to add it to 4.2


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
OK; my only question is I'm not sure how the QWI measure file was generated - it may have been another Heath Special (i.e., used output from my metadata table, but some manually modified labels and such). I can provide the J2J one directly, including the correction that was pointed out on the app description. Will check into the QWI one.

________________________________

**Comment by srt1** [comment]
csv files for J2J variables, containing prior/subsequent quarter counts

[j2j-vars-schema.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1434988/j2j-vars-schema.gz)

**Comment by srt1** [comment]
Now that I am looking at the variables_QWI csv files, I am more suspecting that they were _Lars Specials_. Any suggestion as to how we want to maintain these, preferably linked to our internal metadata table? The labels and descriptions here look completely different from anything in our table.

**Comment by larsvilhuber** [comment]
They may be Lars specials. Best method: synchronize.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
I'll see about updating the labels/descriptions on the QWI table. It's a bit messy, unfortunately - John A originally developed it to keep all of the names and labels that had ever been used, so it can be tricky to identify the active ones; and I don't particularly want to add yet another name and description field...

________________________________

**Comment by larsvilhuber** [comment]
Well, my original source was the same spreadsheet. Glad to know it's now getting reviewed... 😉 (thanks)


I'm not too wed to anything on there - just that it be understandable and right...


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
The canonical version is a tab-delimited version stored in the QWI code version - it gets put into a spreadsheet for editing, and then back. It looks like the latest maintenance on the file was by Camille, adding a number of things for NQWI. 

I think in this case it makes sense to add a number of new fields. The existing ones are used in dataset labels, and I don't think I want to immediately change all of those. It should be reasonably clean to patch  on a few extra variables.

```
schema_name
schema_description
schema_rate_name
schema_rate_description
schema_concept
schema_base
```

Question about **concept**:

The JF/FJF measures (Net Job Flows) have a "Employment" concept, but the JFR/FJFR measures have a "Flow" concept. Was this difference intended? Also The JC/FJC/JCR/FJCR is "Hire", JD/FJD/JDR/FJDR is "Separation." I don't think those concepts are very good descriptions of job creation/destruction measures.

As an alternative, I would suggest that all the measures in the job flow family be categorized as "Flow", both counts and rates.

**Comment by srt1** [comment]
Added point on concept:

The concept for the Turnover variable is "Turnover." (And the name of this variable changes on the Rate file, adding an R - from TurnOvrS to TurnOvrSR). To be honest, I'm not sure to do with this one either. Other concepts are Employment/Hire/Separation/Earnings/[Flow?]. I'd love to get rid of the variable, but it is the one that people always call about because they think it means something. Ideas are welcome...

**Comment by srt1** [comment]
Not that I want to revisit the inconsistent naming conventions again, but the 4.2b-draft schema includes a number of "Internal Names" that were hand-curated by Lars, and don't really bear resemblance to things that I would call internal names. Part of this was probably because of the conflict of the CA/CAR/"EI" variable names. CAR is what we internally call replacement hires, but that conflicts by the CA+R convention for the rate for continuing quarter accessions. I don't use the "+R" convention for the internal names, but they are used in the infrastructure paper.  

There's also the "Z_W1" variable, which Lars uses for the average monthly earnings for B employment. This is annoyingly reflective of the "W1" variable, which is used in the infrastructure document to reference total earnings.

I could just add yet another column to our internal control table, since there is no other way to account for these differences. And I don't particularly want to rehash the whole naming thing again; but do we want to revisit it, or just go with the names Lars set out in 4.2b-draft?

**Comment by larsvilhuber** [comment]
The CA terminology in the schema came from the original specs as published (e.g.  https://www.vilhuber.com/lars/wp-content/papercite-data/pdf/abowdetal2009.pdf ) , and denote the name "Consecutive quarter Accessions" (see def. A9, pg 217,for the microdata definition, which uses 'a2', and def. A69, pg. 224, which uses "CA" (and A70, CS) for the aggregated variable. I attempted to stay consistent with the published specs, not the vagaries of the internal changes over time (I had no hand in making CAR = replacement hires).


I would argue for the 2009 names (which people see, and which "alternate names" (not internal names) refers to), but I can see the issue with the internal system (and would by now be outvoted on the CA/ CS issue).


Note that replacement hires are post-computed, and are thus never mentioned in the 2009 paper.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Yes, we came up with CAR when we added the post-computed measures a few years ago. As you point out, it was not in the 2009 paper, so we had to make up something that seemed reasonable sensible, and those of us who made it up were  oblivious to the "+R" naming convention. You were probably in the general area at the time, but I can't say who participated in which discussions. I'm not a big fan of adding a single rather common letter to the end of a variable name to indicate the rate for just this reason (though we also do it at the beginning of the variables for the status flags). But whatever. No one outside of the walls is particularly getting hurt if they do not see the "CAR" that we keep it as internally.


Second point on "Z_W1" though? The only one we named in the paper was "ZW2" for average earnings for end-of-quarter jobs. "ZW1" was never an established concept, but "W1" was, and it was for all jobs, not just beginning of quarter ones. That's why I named it "ZW2B" originally.






________________________________

**Comment by larsvilhuber** [comment]
Yeah, I'm on the fence about that. You're right that going from A20 to A21 (in the paper) doesn't do it right either. In the very beginning (A1), the sequence is {1,2,3} = {m,b,e} but then for Z earnings, it goes {1,2} = {m,e}. So logically, it should be Z_W1.5... do whatever seems right.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
I never rightly know what to say about this measure, anyway. To me the "2" is intended to indicate the number of consecutive quarters of employment, so "2b" is an alternate version of the concept. For symmetry, I would have named the old concept "2e", but that is not worth revisiting. The whole reason we switched from end to beginning was to be consistent with LODES, which uses earnings for B jobs in quarter 2. Even this is inconsistent with how J2J identifies dominant earnings, which is an average of the two quarters, but that does not get tabulated. Z_W1 looks clearly confusing, since that is what we would name the average earnings for all M jobs, if we reported it. Z_W2B at least has the advantage of not directly conflicting with the existing names. I'll just go with that.  And I will pick up your use of "FH," which does not seem to get used in the internal file. It is rather unfortunate that we mix and match that a bit with H3, but I will just go with it.

________________________________

**Comment by srt1** [comment]
On earlier point, I'm also penciling in the JC/JD/JF measures as "flow", both for rate and count measures. Alternate proposals still can be accepted, but I would request that a count variable and its rate counterpart have the same _concept_. As noted, this was not true for the JF measures in V4.2b-draft.

**Comment by larsvilhuber** [comment]
P.s. You want to check against the status of these things in V4.1.3. We're going to be doing a merge of V4.1.3 and V4.2 (-> V4.2rc1) to check that we don't have any missed things. Not saying we can't overwrite things in V4.1.3 - just to be cognizant of what's coming forward. I *think* I did a comparison a while ago, but not certain.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
One other note, the measures in the 4.2b-draft version appear in a different order than they are presented in the csv files. The files I generate directly from the metadata table come out in the same order that the variables appear in the csv files.

**Comment by larsvilhuber** [comment]
@heathhayward : you promised an updated j2japp schema file. BTW, in crafting that file, can you use a script or something (internally, or here) so that it is kept in sync with the main j2j file?

**Comment by heathhayward** [comment]
Yea, I created one but let me confirm that it's correct.

**Comment by heathhayward** [comment]
The "j2j-vars-schema.gz" file that Stephen posted on Nov 1 is a strange one - shouldn't these be separated out into 3 separate csv files? Seems like gzipping the csv files appended them together.  Also, the OD indicator's Description field looks wrong - they should all start with "Job Flows...".   And shouldn't "Flow" be the Concept for the OD measures?

**Comment by srt1** [comment]
I think there were some open questions when I created it, which we had yet to resolve. I'm not sure why they were wrapped into the same file. I'll review the tickets and refresh myself on where everything was.

________________________________

**Comment by srt1** [comment]
Must be a bug in the creation code - somehow I have "rate" in the description of the OD files. Or I messed up the metadata table a bit. I'll fix it.


Regarding the Concept, we had discussed using hires because these measures were effectively the same as the corresponding measures in the J2J tables. We could still switch them to flow, if we want to focus on the O-D tabulation characteristics. However, we may want to consider how this relates to the QWI measures. In those, we have the JC/JD/JF measures, which I was looking for a concept for. In 4.2b-draft, they are hire/separation/employment, respectively, which to me are odd concepts for these measures. I had proposed calling them "flow", but the concept is completely different from the measures on J2JOD. We'd probably want to use a different word. We could also use "Job Change" or something. Really, they are establishment-level job change, which is far too long, I imagine. Suggestions?

________________________________

**Comment by heathhayward** [comment]
I like "Job Change" as a concept for those measures.

**Comment by srt1** [comment]
On the _DESCRIPTION_ for the **J2JOD** measures:

This was an oversight. In my metadata table, the J2J and J2JOD measures are considered the same, but I have separate columns to provide _Indicator Name_ for J2J vs. J2JOD. However, I never addressed the _Description_ to be used for J2JOD. Hence, it was picking up weird stuff. Do we have a blurb that we should use for those measures?

**Comment by heathhayward** [comment]
Indicator Variable,Indicator Name,Description
EE,Job-to-Job Flows (Continuous Employment),Job flows with no observed nonemployment spell
AQHire,Job-to-Job Flows (Brief Nonemployment),Job flows with a short nonemployment spell
EES,Stable Job-to-Job Flows (Continuous Employment),Job flows from stable employment into stable employment with no observed nonemployment spell
AQHireS,Stable Job-to-Job Flows (Brief Nonemployment),Job flows from stable employment into stable employment with a short nonemployment spell

**Comment by srt1** [comment]
That'll do - thanks.

________________________________

**Comment by srt1** [comment]
Erika:


Can I ask you to weigh in (perhaps again) on the "Concept" field in the description of the J2JOD measures? On the J2J data, the EEHire/AQHire fields have a "Hires" concept. Heath had suggested a "Flow" concept for the corresponding measures EE/AQHire on the J2JOD data, though I think Lars and I argued that tabulating the same measure by origin characteristics does not change the "concept" of the measure, so it should still be "Hires". There are, of course, no "Separations" measures in J2JOD. This is probably a weak preference of ours - I don't think Heath's characterization of the concept is bad; it's largely how we choose to present it.


Links to schema below:

https://lehd.ces.census.gov/data/schema/V4.2b-draft/lehd_public_use_schema.html#_job_to_job_flow_counts_j2j

https://lehd.ces.census.gov/data/schema/V4.2b-draft/lehd_public_use_schema.html#_job_to_job_flow_origin_destination_j2jod


We would like to finalize this for schema version 4.2. Thanks for any thoughts you may have on this.


Stephen

________________________________

**Comment by srt1** [comment]
@larsvilhuber 

Do you have an opinion on the "Job Change" concept for job creation/destruction/flows?

I have updates pending for qwi_measures.csv and qwir_measures.csv, and I think that was the open question.  This is in addition to the j2j ones, awaiting Erika's feedback.

**Comment by larsvilhuber** [comment]
I want to split this ticket. 

- #78  handles the content of the existing qwi*_variables files. 
- #71 (this ticket) handles the addition of two new fields describing variables

**Comment by srt1** [comment]
That's fine, but ultimately I will provide one set of csv files that addresses both tickets.

________________________________

**Comment by larsvilhuber** [comment]
@srt1 For this ticket, I would like to suggest splitting this file off, into a consolidated (maybe) file indexed by `Indicator Variable`, with two new columns `Quarters_Required_Prior,Quarters_Required_Subsequent`

The key reason is that up until now, the core `qwi_variables.csv` etc files have hewed to existing well-established metadata schemas (DDI etc.) in terms of content. With the addition of this information, we are moving into more technical, less user-documentation oriented terrain.

**Comment by larsvilhuber** [comment]
@srt1 Call it the "lehd_lags.csv" file, and generate it separately from the variable labels. Or "lags_qwi.csv" and "lags_j2j.csv", which would also allow for a "lags_j2japp.csv".

**Comment by srt1** [comment]
If you like, I can create the separate files. I would do QWI and J2J separately. There is a bit of a conceptual difference - both are lags relative to their release series, but the QWI ones also represent the leading/lagging quarters of microdata required to calculate the measure. For J2J, you need to add 1, because all measures already require B/E to be calculable.


________________________________

**Comment by srt1** [comment]
I don't have a very strong opinion on this, but agree that for the sake of consistency, it would make sense to use either 'hires/separations' or 'flow to employment/flow to nonemployment' for the same types J2J flows on the counts/rates and OD files.  It doesn't make much sense to change the concept for the same job move just because on one file we are seeing both origin and destination characteristics of the job move.


Erika



________________________________

**Comment by srt1** [comment]
Managed to put together the "lags" files from QWI and J2J metadata tables. Need to do some checking, should have them ready Tues morning.

**Comment by srt1** [comment]
Files with lags for QWI and J2J measures.

[lags_j2j.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1572166/lags_j2j.csv.gz)
[lags_qwi.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1572167/lags_qwi.csv.gz)

**Comment by larsvilhuber** [comment]
OK, so


lags_qwi contains the ACTUAL data lags necessary to compute a variable.


lags_j2j contains the (ACTUAL - 1) data lags necessary to compute a variable.


Really?


Can we for public consumption please make it so there is ONE description for each of these? (and somewhere down the road, maybe the internal processes can then use the -1 rule to get at the number they are using now).


Or I'm misunderstanding something...


lags_j2j.csv:MainB,0,0
lags_j2j.csv:MainE,0,0
lags_qwi.csv:Emp,1,0
lags_qwi.csv:EmpEnd,0,1

makes no sense...



--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Both files provide the number of quarters incremented from the outer bounds of the public use time series that a variable will not be available. This is probably the most reasonable way to present the information here.

________________________________

**Comment by larsvilhuber** [comment]
Ah. I was interpreting in the microdata way, as quarters necessary to compute the data. Not the same thing, for a given publication strategy. Thanks. Working on it.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Yes; it happens that the outer bounds of the J2J are internal to the outer bounds of QWI by (at least) one on either end. The  interested user can learn about why that is in the documentation of the calculations from the microdata; but the average data user only really needs to know the lag relative to the series.

________________________________

**Comment by larsvilhuber** [comment]
@srt1 @heathhayward : would you review the text I added : [lehd_public_use_schema.asciidoc#metadata-on-indicator-availability](https://github.com/labordynamicsinstitute/qwi_schemas/blob/b012328581cc0caf963db7e2c44013ffe847ae50/formats/V4.2-rc1/lehd_public_use_schema.asciidoc#metadata-on-indicator-availability)

**Comment by srt1** [comment]
The only caveat I would give is that the data ranges for J2JOD data vary by the combination of states; hence, you need to look at the  j2jod_ST_avail.csv file for those.

________________________________

**Comment by larsvilhuber** [comment]
No caveats. Please suggest text that correctly describes how these files are to be used.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Suggestion:

Each Indicator potentially requires leads and/or lags of data to be computed, and thus may not be available for certain time periods. Only two QWI will be available for all quarters of the time span described by start and end in the version.txt files: EmpTotal and Payroll. For each indicator, the following files contain the quarters of data required to be available relative to the overall date range described in the metadata for the release. The date range for QWI, QWIR, J2J, and J2JR can be found in version.txt; the date range for J2JOD can be found in avail.csv.

_Note, it looks like you have a hanging "The files are structured as follows" - were you going to stick a link there?_

**Comment by larsvilhuber** [comment]
There is a link in the HTML version, but the HTML doesn't render on Github, so I pointed you at the ASCIIDOC version.


Updating now.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by larsvilhuber** [comment]
@srt1 : review and signoff.

**Comment by heathhayward** [comment]
lags metada files look good to me.

**Comment by srt1** [comment]
I'm sorry, I'm still not very adept at navigating this; is there somewhere I can look to see the at-least-partially rendered version of this? Right now I'm just looking at changesets.

**Comment by larsvilhuber** [comment]
https://github.com/labordynamicsinstitute/qwi_schemas/blob/0dc69a04551a6888758df27af5b4eb07745740a3/formats/V4.2-rc1/lehd_public_use_schema.asciidoc

**Comment by srt1** [comment]
Looks good
