### ISSUE TITLE
Description on J2JOD earnings measures reversed

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#72]
The variable and indicator name are correct, the descriptions of the origin-destination earnings are reversed. There had earlier been a general mixup with these variables, I had to flip everything. It looks like I missed the "App description" in my metadata table.

Correction attached.

[variables_j2jod.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1360928/variables_j2jod.zip)

**Comment by heathhayward** [comment]
Here is the replacement for the variables_j2japp.csv file for the 4.2b-draft schema.  Between this file and Stephen's variables_j2jod.csv file above, this issue should be resolved.

[variables_j2japp.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1362713/variables_j2japp.zip)

**Comment by larsvilhuber** [comment]
This is fixed. It is an edit of an error in a release, so no new version (as per versioning policy). I will, however, create a new "github release" with a dotted version.

**Comment by heathhayward** [comment]
Doesn't look like either the j2jod or j2japp csv files were actually fixed/replaced at https://lehd.ces.census.gov/data/schema/V4.2b-draft/variables_j2japp.csv or https://lehd.ces.census.gov/data/schema/V4.2b-draft/variables_j2jod.csv.  Did I drop the ball on this by not pushing Chaoling to update these files on the webservers?

**Comment by srt1** [comment]
I really don't know...

________________________________

**Comment by larsvilhuber** [comment]
It was implemented in the repository at 1941bc9 . It is available for the usual pull-push workflow in the LEHD repository.

**Comment by heathhayward** [comment]
OK, I've asked Chaoling to push the update.  No further updates are in the repository yet, correct?  I don't want to push something that's not ready...

**Comment by larsvilhuber** [comment]
This was the last commit to the `lehd` branch, which is the only one being incorporated into Census codebase. So the answer is: No, no further updates.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
The "j2japp.csv" file was implemented into the repository, but the "j2jod.csv" was not (looks like https://github.com/labordynamicsinstitute/qwi_schemas/blob/master/formats/V4.2b-draft/variables_j2jod.csv is still wrong).  Lars, can you replace the latter file with the file Stephen provided on October 5 above?

**Comment by larsvilhuber** [comment]
@heathhayward : this should be fixed now in the LEHD branch. It is available for the usual pull-push workflow in the LEHD repository.

**Comment by heathhayward** [comment]
this has been implemented on LEHD production.
