### ISSUE TITLE
2017 GeoVintage Upgrade (2018Q1)

### ISSUE THREAD

**Issue by norwo307** [labordynamicsinstitute/qwi_schemas#73]
We are upgrading to a 2017 GeoVintage starting 2018Q1.

- We need to specify the new schema number.

- We need to provide updated label_geography.csv files for every state.

- We need to provide updated shapefiles for every state.

**Comment by larsvilhuber** [comment]
Waiting for updated geography files and shapefiles.

The new version number is likely to be 4.3.0

**Comment by larsvilhuber** [comment]
Correction: 4.2.0

**Comment by larsvilhuber** [comment]
@norwo307 @heathhayward : are there any changes to this?

**Comment by norwo307** [comment]
There are no updates to the label_geography files.

**Comment by larsvilhuber** [comment]
@heathhayward : any updates to shape files?

**Comment by larsvilhuber** [comment]
@heathhayward : 

is this statement still correct:

> The 2015 vintage  of   https://www.census.gov/geo/maps-data/data/tiger-line.html[Census TIGER/Line geography] is used for all tabulations as of the R2015Q4 release.

**Comment by heathhayward** [comment]
Yes. We will want to update this to say" 2016" as of the R2017Q1 release (which may be when we release this schema version - not sure of the timing of all of this).

**Comment by larsvilhuber** [comment]
This ticket is about 2017 Geovintage as of 2018Q1. I presume the text should then say


>The 2017 vintage of  https://www.census.gov/geo/maps-data/data/tiger-line.html[Census<https://www.census.gov/geo/maps-data/data/tiger-line.html%5BCensus> TIGER/Line geography] is used for all tabulations as of the R2018Q1 release.


Fixing (if necessary) the text in the older V4.1.x versions is a different ticket. Feel free to submit, I will not be handling them this week.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
that's correct. sorry.   We started using 2015 TIGER as of R2015Q4, 2016 TIGER as of R2016Q4, and will transition to 2017 in R2018Q1.

**Comment by larsvilhuber** [comment]
On 2017 Geovintage update:


lehd_shapefiles.html documents use of TIGER2016. When do you think you'll have the updated 2017 shape files to me, and presumably that entire segment (in write_shapefiles.sh generating it) needs to be updated.


Lars


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
I'll look at it first thing in the morning.  If everything is in order, I could have the updated shapefiles to you by COB tomorrow.

**Comment by heathhayward** [comment]
[lehd_shp_gb.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1575674/lehd_shp_gb.zip)
[lehd_shp_gc.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1575676/lehd_shp_gc.zip)
[lehd_shp_gw.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1575677/lehd_shp_gw.zip)
[lehd_shp_gm.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1575678/lehd_shp_gm.zip)
[lehd_shp_gs.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1575679/lehd_shp_gs.zip)

**Comment by heathhayward** [comment]
In terms of updates to https://github.com/labordynamicsinstitute/qwi_schemas/blob/master/formats/V4.2b-draft/lehd_shapefiles.html, the "Sources" section should update "2016" to "2017" in the shapefile names and URLs.  I don't think anything needs to change.  Here are the label_geography files that match my shapefiles.  I believe these are only used for QA purposes, as Camille prefers that we use her versions of these files created from Production. I'll email them to her so she can compare...

[label_geography.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1575709/label_geography.zip)

**Comment by larsvilhuber** [comment]
Some notes on label_geography.zip - this is useful.


a) the one in the repo has quoted names for all levels of geo, your file does not have quoted names for the state-level names and for some WIAs

b) your version has apostrophes in some names, which Camille's version does not

c) your version has "city"  added to quite a few names. which is it? (Baltimore, St.Louis, etc.). Needed?

d) You have PR and VI - the production version does not, because not currently being produced.

e) For some reason, the sort order on the production files is different (WIB's interspersed in the listing, rather than at the end)


I have copied b and e over into the "official files", I have ignored a, c, d.


This should be disambiguated on the production side between you and Camille.

--

Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
The differences are mostly due to sourcing - mine from TIGER and the Production version from the BMF (sourced from the GRF-N).  We should use the Production version since it more closely links to the QWI tabulation areas.

**Comment by larsvilhuber** [comment]
@heathhayward : please review the ASCIIDOC version of the shapefile doc.

**Comment by heathhayward** [comment]
https://github.com/labordynamicsinstitute/qwi_schemas/blob/V4.2-rc1/formats/V4.2-rc1/lehd_shapefiles.asciidoc looks good to me.
