### ISSUE TITLE
Change to 2017 NAICS codes

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#74]
The 2017 NAICS codes are being reported with the 2017Q1 ES202 data submission (2017Q4 QWI production). The R2017Q4 will still be on 2012 NAICS, but I expect that R2018Q1 will be on 2017 NAICS. There are some minor changes to the industry code list.

_(Schema number??)_

**Comment by larsvilhuber** [comment]
Will be in 4.2.0

**Comment by larsvilhuber** [comment]
Needs
- new industry code lists
- change to description

**Comment by srt1** [comment]
Thanks. Will put those together shortly.


________________________________

**Comment by srt1** [comment]
I propose adding **industry_level** to the _label_industry.csv_ schema file, to be parallel with the _label_geography*csv_ files. It's a useful piece of information.

**Comment by srt1** [comment]
Industry codes in 2017 NAICS. For example change, note that 4521 is gone, 4522 is new (department stores merged with discount stores in 2017). There are other related changes in that range.

[label_industry.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1472934/label_industry.csv.gz)

**Comment by srt1** [comment]
misclassified the industry_level on the (00, 000, 0000) records. This is corrected.

[label_industry.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1479733/label_industry.csv.gz)

**Comment by larsvilhuber** [comment]
Needs further integration (scripts)

**Comment by larsvilhuber** [comment]
This is working in all scripts.
