### ISSUE TITLE
Clarify contents of variables_qwi*.csv

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#78]
There is some hand-curated and manual labor in these files. We are checking to see what the definitive labels should be and how to generate them. This is partially addressed in the discussion in #71

**Comment by heathhayward** [comment]
Should we call these "variables_qwi.csv" and "variables_qwir.csv" to match the format of j2j?

**Comment by srt1** [comment]
We do.


variables_qwi.csv

variables_qwir.csv


I think we're just getting confused in the ticket discussion.

________________________________

**Comment by srt1** [comment]
_The following a comment regarding the "Concept" for J2JOD counts from Erika (see previous discussion in #71)_

I don't have a very strong opinion on this, but agree that for the sake of consistency, it would make sense to use either 'hires/separations' or 'flow to employment/flow to nonemployment' for the same types J2J flows on the counts/rates and OD files. It doesn't make much sense to change the concept for the same job move just because on one file we are seeing both origin and destination characteristics of the job move. 

Erika

**Comment by srt1** [comment]
Reference discussion in #71 regarding the various QWI measures. I believe that most of the questions were resolved, but I think the one last open one was what _Concept_ to apply to the JF/JD/JC family of measures. I suggested "Job Change", which is really shorthand for "Firm Job Change", as these are all establishment growth and decline concepts. Any thoughts on this? (@larsvilhuber )

**Comment by larsvilhuber** [comment]
"Job flows" would be the correct term for these - "gross job flows" are job creation and destruction, and "net job flows" is it's own variable, the entire class is "Job flows" in the entire economics literature.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
Fine - will update concept.

________________________________

**Comment by srt1** [comment]
Updated QWI variables tables. I hope.

[variables_qwi.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1577019/variables_qwi.csv.gz)
[variables_qwir.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1577020/variables_qwir.csv.gz)
