### ISSUE TITLE
Update to variables_j2j*.csv - description, concept

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#79]
Cleanup variables_j2j*csv files. The description needs to be corrected for OD measures.

**Comment by srt1** [comment]
Latest version of files. My understanding from Erika's response (logged in #71) was that we should keep the concept for the OD counts as _Hires_. These files should have updated descriptions, with the OD descriptions coming from Heath. Please review and let me know if you see anything.

[variables_j2j.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1572307/variables_j2j.csv.gz)
[variables_j2jod.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1572308/variables_j2jod.csv.gz)
[variables_j2jr.csv.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1572309/variables_j2jr.csv.gz)

**Comment by heathhayward** [comment]
[frustrated sigh].  I'll have to request changes to the application code now that OD and Count indicators have the same concept.

**Comment by larsvilhuber** [comment]
Isn't there an emoji for that?


😞😩


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
I left a comment on commit 4a5369c - that correction should also apply to v4.2b-draft. If we want to bother - some descriptions of the OD measures are wrong.

**Comment by heathhayward** [comment]
Since the j2japp file combines the j2j, j2jr, and j2jod indicators together, there's no longer a way to differentiate the od and count indicators.  So we need to add another field ("type" or "category"?) to the j2japp file - or I guess I can keep my own copy of the j2japp file that keeps the concept field how J2J Explorer needs it.  Thoughts?

**Comment by srt1** [comment]
Perhaps flags for J2J/J2JR/J2JOD?

________________________________

**Comment by larsvilhuber** [comment]
If my memory serves me right, what you needed was a grammar indicator. Or a verb?


Define the J2JAPP file as an add-on to the existing formal metadata. I.e., match on "Indicator variable" what you need, onto a concatenated file or each individual file. That would have the least amount of duplication.


We can host the file in the schema, or not. (Fundamentally I think this is an application specific mapping of public information - the schema - into idiosyncratic app functionality, and should be maintained by the app developers. On the off-chance that others might consider it useful, it makes sense to keep it in the schema)


We should probably EXclude the variables_j2japp.csv from the generic LEHD_Publicuse_schema.html, but continue to document it in the j2japp*html.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
I'm fine removing it from the schema and making j2japp.csv something the app-developers keep in house. It would certainly make coordination easier and protect the code from these schema iterations.

**Comment by larsvilhuber** [comment]
We have split this task into three: 

- updating the variables_j2japp.csv to describe the *additional* variables created in the app and not in the raw CSV file (this ticket #79)
- adding functionality to the app to detect context and grammar (will be done in the app, combining WHERE the variable is (j2j or j2jod) and the existing metadata (variables_j2j.csv and variables_j2jod.csv)
- discussing the concepts in use globally in the J2J documentation (#78 )

**Comment by larsvilhuber** [comment]
This ticket is probably closed for now.
