### ISSUE TITLE
Finalize j2japp metadata

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#80]
- additional rows as computed by the app, for J2J

**Comment by heathhayward** [comment]
[variables_j2japp.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1577114/variables_j2japp.zip)

Stephen, please confirm the Base value for the earnings measures (and change the Alternate Names if you like).

**Comment by larsvilhuber** [comment]
The alternate names are names that might have appeared in other (historical or current) publications. For QWI, that was the Abowd et al (2009) paper (with some fuzziness). For J2J, these are the internal ones. What to use for the J2JAPP is unclear - feel free to improvise.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
As far as alternate names, we can follow the existing conventions, and reuse some names.

```
J2J              j2j_doma2
J2JS             fj2j_doma2
J2JSEarn_Orig    fj2j_doma2_jfqearn
J2JSEarn_Dest    fj2j_doma2_kfqearn
```

**Comment by srt1** [comment]
As far as the earnings calculation, I believe that is the correct calculation of the average earnings. You are taking the average of the earnings from the EE and AQ transitions, weighted by the count for each. However, the base should simply be **J2JS**. The full calculation should be included in our documentation, if it isn't there already.

**Comment by srt1** [comment]
Note, we may also want to provide a supplementary file for the lags_j2j.csv file for the 4 measures here. They will have the same lead/lag as the corresponding AQHire measures.

**Comment by srt1** [comment]
Just kicking my own hand-crafted versions back to Heath for review.

[lags_j2japp.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1577258/lags_j2japp.zip)

[variables_j2japp.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/1577241/variables_j2japp.zip)

**Comment by larsvilhuber** [comment]
See also #71 for the lags issue.

**Comment by larsvilhuber** [comment]
@heathhayward : please review.

**Comment by heathhayward** [comment]
lags_j2japp.zip and variables_j2japp.zip look good to me.
