### ISSUE TITLE
Remove lehd_j2jexplorer_schema documentation until J2J app transitions to V4.2

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#81]
the app is currently on V4.2a-draft. To avoid user confusion, remove the documentation (but not the metadata)

**Comment by larsvilhuber** [comment]
This is fine, since the documentation is just a view onto the metadata, and does not impact usability.

**Comment by heathhayward** [comment]
Thanks for creating this issue.

**Comment by heathhayward** [comment]
Only change I recommend would be: in Indicators section, let's list all 4 "variables_j2j*.csv" files (since j2japp now only includes the app-created indicators).  otherwise this looks good - I like the addition of the Metadata section at the bottom.

**Comment by larsvilhuber** [comment]
@srt1 @heathhayward : why are the first two rows in the j2japp file, when they appear to be identical to variables/indicators in the standard j2j file:

j2japp:


J2J | j2j_doma2 | sJ2J | Job-to-Job Flows | Job flows with a short or no observed nonemployment spell | Count | Hire | 1
-- | -- | -- | -- | -- | -- | -- | --
J2JS | fj2j_doma2 | sJ2JS | Stable Job-to-Job Flows | Job flows from stable employment into stable employment with a short or no observed nonemployment spell | Count | Hire | 1

j2j:

J2JHire | j2j_doma2 | sJ2JHire | Job-to-Job Hires | Hires following a separation (short or no observed nonemployment spell) | Count | Hire | 1
-- | -- | -- | -- | -- | -- | -- | --

EEHireS | fee_doma2 | sEEHireS | Stable Job-to-Job Hires (Continuous Employment) | Hires to stable employment following a separation from stable employment with no observed nonemployment spell | Count | Hire | 1
-- | -- | -- | -- | -- | -- | -- | --

**Comment by srt1** [comment]
J2J is the same as J2JHire, just as EE on measures_j2j is the same as EEHire on measures_j2jod. EEHireS is a different measure than J2JS, which has no equivalent on the core file - it is the sum of EEHireS and AQHireS.

But I suspect I am missing the point of the question...

**Comment by larsvilhuber** [comment]
The point of the question was:


the first two lines are from variables_j2japp.csv , which was intended to be a supplement to the core variables_j2j.csv. So if J2J is just a "rename" of J2JHire, should it be on the file? Has the J2J team signed off on the alternate description of that variable?


if yes, then fine, but that should be explained in the surrounding text.


For J2JS != EEHireS, without looking at the data, and only at the definitions, that is an EXTRAordinarily subtle point. But I guess I'm several months late for that.


I'm fine with J2JS as long as it is defined in the J2J long and short documentation.


This is not an urgent item, we can punt the whole thing into V4.2-rc2 or even later. However, strictly speaking, we can *add* variables_j2japp.csv into a later 4.2.x release, but we cannot REMOVE items from it if it is added. That's a decision that we'll have to make.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by srt1** [comment]
It's not a rename, really; it is the creation of an identical variable using components on the J2JOD table. But again, not a good discussion to have in a ticket. I'm lost.


________________________________
