### ISSUE TITLE
SAS import programs - do we want them going forward?

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#87]
More of a question:

We will be removing the schema-related files from the QWIPU distribution (label*, column_definitions.txt, status_flag_description.txt), in favor of redirecting users to the schema. We also provide a SAS program as part of the QWIPU distribution to assist users with reading in the data. I am assuming that will be discontinued as well, since it uses the label* files, which will no longer be there. Should we develop and distribute this kind of facility elsewhere, possibly as part of the schema?

**Comment by heathhayward** [comment]
I don't have any data or anecdotes that the SAS programs are being used.  Do you? I'm fine discontinuing this, but we should check with Lars.

**Comment by larsvilhuber** [comment]
Two answers here:
- I have added the original files to my version of the readin programs at https://github.com/labordynamicsinstitute/qwi-download/releases/tag/V4.1
- The generic SAS readin program was stored together with V4.0, and so will remain available there.
