### ISSUE TITLE
Fix EOL and character encoding issues in the label_geography* files

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#88]
In V4.2.0, we found several instances of EOL and character encoding issues in the label_geography files.  This caused the QWI data loader to fail.  Those issues have been fixed on https://lehd.ces.census.gov/data/schema/V4.2.0/ but should be pushed through the system elsewhere.  thanks.

**Comment by larsvilhuber** [comment]
@heathhayward : could you check out if this release works? For testing, the validation scripts on your test server can reference this location

https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.2.0/

instead of the default one on LEHD servers.

**Comment by heathhayward** [comment]
I'm seeing some blank lines and spanish character encoding issues in some PR labels here: https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.2.0/label_geography.csv.  All of the other files look good - I don't see the PR label encoding issue in https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.2.0/label_geography_metro.csv and all the state-based files look to have their EOL issues fixed.

**Comment by larsvilhuber** [comment]
Hm. I converted all to UTF-8 but did not check PR. I thought I had removed blank lines from the concatenated ones.


I'll check what's going on.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by larsvilhuber** [comment]
Dang. This actually doesn't look like the final version I worked on. I need to figure out which working copy I did NOT push...


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by larsvilhuber** [comment]
@heathhayward : so at present all label_geography_*.csv files are UTF-8, and have Unix EOL. They should ideally stay that way, and ideally the code should check for that. 

Have another look now at the latest.

**Comment by heathhayward** [comment]
The EOL issues are fixed.  But I'm still seeing names like: "San GermÃ¡n, PR", "MayagÃ¼ez, PR", "DoÃ±a Ana, NM" in https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.2.0/label_geography.csv.  

Additionally, the "label_geography_[ST/metro].csv" files are also now incorrectly displaying these spanish characters in places where they were correct yesterday.  For example, yesterday  https://labordynamicsinstitute.github.io/qwi_schemas/formats/V4.2.0/label_geography_co.csv correctly showed ,"Cañon City, CO", but now it's displayed as "CaÃ±on City, CO".  UTF-8 should do it correctly - we've had issues in SAS when switching between latin1 and UTF-8 encoding...

**Comment by larsvilhuber** [comment]
Because they were not coded in UTF-8...


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346

________________________________

**Comment by heathhayward** [comment]
OK, I guess this is good to go then.

**Comment by larsvilhuber** [comment]
Implemented as V4.2.0.1, but continues to be referenced as V4.2.0
