### ISSUE TITLE
Replace lehd_shp_gw.zip as part of V4.3.1

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#95]
Due to a WIB definition change in Iowa, the "lehd_shp_gw.zip" needs to be updated.  I'll add the file here when it's ready.

**Comment by heathhayward** [comment]
[lehd_shp_gw.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/2530801/lehd_shp_gw.zip)

**Comment by larsvilhuber** [comment]
Not closed until released into master.

**Comment by larsvilhuber** [comment]
Released as https://github.com/labordynamicsinstitute/qwi_schemas/releases/tag/V4.3.1
